import * as React from 'react';
import { createRoot } from 'react-dom/client';
import Typography from '@mui/material/Typography';
import {
    FileBrowser,
    FileNavbar,
    FileToolbar,
    FileList,
    FileContextMenu,
} from '../dist/chonky.esm.js';
import { ChonkyIconFA } from '../../chonky-icon-fontawesome';
import { ChonkyActions } from '../dist/index.js';

const App = () => {
    const pathEntries = ['test', 'folder'];
    const [appendInfo, setAppendInfo] = React.useState('Test Info');

    const files = [
        {
            id: 19,
            name: '1',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: true,
            droppable: true,
            size: null,
            modDate: '2024-12-27T01:51:38.187363',
            thumbnailUrl: null,
            childrenCount: 1,
            childrenIds: ['20','21'],
            icon: 'folder',
            color: '#c19a25',
            children: [
                {
                    id: 20,
                    name: '2asd',
                    isDir: true,
                    parentId: 19,
                    ext: null,
                    isHidden: false,
                    isSymlink: false,
                    isEncrypted: false,
                    openable: true,
                    selectable: true,
                    draggable: true,
                    droppable: true,
                    size: null,
                    modDate: '2024-12-27T01:51:38.187363',
                    thumbnailUrl: null,
                    childrenCount: 0,
                    childrenIds: null,
                    icon: 'folder',
                    color: '#c19a25',
                },
                {
                    id: 21,
                    name: '3sadsadsd',
                    isDir: true,
                    parentId: 19,
                    ext: null,
                    isHidden: false,
                    isSymlink: false,
                    isEncrypted: false,
                    openable: true,
                    selectable: true,
                    draggable: true,
                    droppable: true,
                    size: null,
                    modDate: '2024-12-27T01:51:38.187363',
                    thumbnailUrl: null,
                    childrenCount: 0,
                    childrenIds: null,
                    icon: 'folder',
                    color: '#c19a25',
                },
            ],
        },
        {
            id: 25,
            name: '78',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2024-12-27T02:23:15.578713',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 26,
            name: '89',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: true,
            droppable: true,
            size: null,
            modDate: '2024-12-27T02:23:19.202724',
            thumbnailUrl: null,
            childrenCount: 1,
            childrenIds: ['27'],
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 22,
            name: '9',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: true,
            droppable: true,
            size: null,
            modDate: '2024-12-27T01:56:13.381292',
            thumbnailUrl: null,
            childrenCount: 1,
            childrenIds: ['23'],
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 15,
            name: 'asdas asd34',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2024-12-27T00:00:38.187778',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 2,
            name: 'IMG2',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2025-01-09T03:50:10',
            thumbnailUrl: null,
            childrenCount: 1,
            childrenIds: ['9'],
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 3,
            name: 'PDF',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2024-12-25T07:49:51.016128',
            thumbnailUrl: null,
            childrenCount: 1,
            childrenIds: ['11'],
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 43,
            name: 'PDF1',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2025-01-06T05:24:35.060729',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 6,
            name: 'PNG',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2024-12-26T05:08:51.363069',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 8,
            name: 'Second Test',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2024-12-26T05:12:25.819471',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 42,
            name: 'Services IT test',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2025-01-06T04:57:22.825565',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 29,
            name: 'SVG V',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2025-01-06T05:24:44.596494',
            thumbnailUrl: null,
            childrenCount: 10,
            childrenIds: ['30', '31', '33', '36', '37', '38', '39', '40', '41', '45'],
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 5,
            name: 'Test',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2024-12-26T04:42:04.79449',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 1,
            name: 'Test Linux',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: true,
            droppable: true,
            size: null,
            modDate: '2025-01-09T03:50:10',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 7,
            name: 'TestPic',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2024-12-26T05:10:36.409541',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 4,
            name: 'TXT',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2024-12-26T04:30:31.555114',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 16,
            name: 'Valy',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2024-12-27T00:06:41.83067',
            thumbnailUrl: null,
            childrenCount: 2,
            childrenIds: ['17', '18'],
            icon: 'folder',
            color: '#c19a25',
        },
        {
            id: 44,
            name: 'Vlado',
            isDir: true,
            parentId: 0,
            ext: null,
            isHidden: false,
            isSymlink: false,
            isEncrypted: false,
            openable: true,
            selectable: true,
            draggable: false,
            droppable: true,
            size: null,
            modDate: '2025-01-06T05:25:56.412535',
            thumbnailUrl: null,
            childrenCount: 0,
            childrenIds: null,
            icon: 'folder',
            color: '#c19a25',
        },
    ];
    return (
        <div style={{ height: 900 }}>
            <FileBrowser
                // darkMode={theme !== "light"}
                iconComponent={ChonkyIconFA}
                // darkMode={true}
                files={files}
                folderChain={pathEntries.map((name, idx) => ({
                    id: `${idx}`,
                    name,
                }))}
                // fileActions={fileActions}
                // onFileAction={handleFileAction}
                disableDefaultFileActions={[
                    ChonkyActions.SortFilesByName.id,
                    ChonkyActions.SortFilesByDate.id,
                    ChonkyActions.SortFilesBySize.id,
                    ChonkyActions.ToggleShowFoldersFirst.id,
                    ChonkyActions.ToggleHiddenFiles.id,
                    // ChonkyActions.FocusSearchInput.id,
                ]}
            >
                <FileNavbar />
                <FileToolbar>
                    <div className="chonky-infoContainer">
                        <Typography variant="body1" className="chonky-infoText">
                            {appendInfo}
                        </Typography>
                    </div>
                </FileToolbar>
                <FileList />
                <FileContextMenu />
            </FileBrowser>
        </div>
    );
};

const root = createRoot(document.getElementById('root')!);
root.render(<App />);
